name: Push data to Elasticsearch

on:
  workflow_run:
    workflows: ["Validate JSONs"]
    branches: ["main"]
    types: [completed]

jobs:
  push_to_elasticsearch:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Export to Elasticsearch
        env:
          ES_API_KEY: ${{ secrets.ELASTICSEARCH_API_KEY }}
          ES_HOST: ${{ secrets.ELASTICSEARCH_HOST }}
          ES_PORT: ${{ secrets.ELASTICSEARCH_PORT }}
        run: pip install -r requirements.txt && python load_elastic.py
